"""Seed the database with sample data for immediate usability."""
import datetime
from sqlalchemy.orm import Session
from app.models import User, Listing, ListingImage, Amenity, Booking, Review, Wishlist
from app.auth import get_password_hash

AMENITIES_DATA = [
    # Essentials
    {"name": "Wifi", "icon": "wifi", "category": "Essentials"},
    {"name": "Kitchen", "icon": "kitchen", "category": "Essentials"},
    {"name": "Washer", "icon": "washer", "category": "Essentials"},
    {"name": "Dryer", "icon": "dryer", "category": "Essentials"},
    {"name": "Air conditioning", "icon": "ac", "category": "Essentials"},
    {"name": "Heating", "icon": "heating", "category": "Essentials"},
    {"name": "TV", "icon": "tv", "category": "Essentials"},
    {"name": "Iron", "icon": "iron", "category": "Essentials"},
    # Features
    {"name": "Pool", "icon": "pool", "category": "Features"},
    {"name": "Hot tub", "icon": "hottub", "category": "Features"},
    {"name": "Free parking", "icon": "parking", "category": "Features"},
    {"name": "EV charger", "icon": "ev", "category": "Features"},
    {"name": "Gym", "icon": "gym", "category": "Features"},
    {"name": "BBQ grill", "icon": "bbq", "category": "Features"},
    {"name": "Breakfast", "icon": "breakfast", "category": "Features"},
    {"name": "Indoor fireplace", "icon": "fireplace", "category": "Features"},
    # Location
    {"name": "Beachfront", "icon": "beach", "category": "Location"},
    {"name": "Waterfront", "icon": "water", "category": "Location"},
    {"name": "Ski-in/Ski-out", "icon": "ski", "category": "Location"},
    # Safety
    {"name": "Smoke alarm", "icon": "smoke", "category": "Safety"},
    {"name": "Carbon monoxide alarm", "icon": "co", "category": "Safety"},
    {"name": "Fire extinguisher", "icon": "fire_ext", "category": "Safety"},
    {"name": "First aid kit", "icon": "first_aid", "category": "Safety"},
    # Extras
    {"name": "Workspace", "icon": "workspace", "category": "Extras"},
    {"name": "Self check-in", "icon": "checkin", "category": "Extras"},
    {"name": "Luggage dropoff", "icon": "luggage", "category": "Extras"},
    {"name": "Long term stays", "icon": "longterm", "category": "Extras"},
    {"name": "Pets allowed", "icon": "pets", "category": "Extras"},
]

USERS_DATA = [
    {
        "email": "sarah@example.com",
        "password": "password123",
        "first_name": "Sarah",
        "last_name": "Johnson",
        "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
        "bio": "Superhost with 5+ years of experience. I love sharing my beautiful spaces with travelers from around the world.",
        "is_host": True,
        "is_superhost": True,
    },
    {
        "email": "marco@example.com",
        "password": "password123",
        "first_name": "Marco",
        "last_name": "Rivera",
        "avatar_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
        "bio": "Architecture enthusiast and passionate host. My places are designed for comfort and style.",
        "is_host": True,
        "is_superhost": True,
    },
    {
        "email": "emily@example.com",
        "password": "password123",
        "first_name": "Emily",
        "last_name": "Chen",
        "avatar_url": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
        "bio": "Travel lover and host. My mountain retreats offer the perfect escape from city life.",
        "is_host": True,
        "is_superhost": False,
    },
    {
        "email": "james@example.com",
        "password": "password123",
        "first_name": "James",
        "last_name": "Wilson",
        "avatar_url": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
        "bio": "City dweller with a love for design. My apartments are in the heart of the action.",
        "is_host": True,
        "is_superhost": False,
    },
    {
        "email": "guest@example.com",
        "password": "password123",
        "first_name": "Alex",
        "last_name": "Thompson",
        "avatar_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop",
        "bio": "Love exploring new places!",
        "is_host": False,
        "is_superhost": False,
    },
]

LISTINGS_DATA = [
    {
        "host_idx": 0,
        "title": "Stunning Oceanfront Villa with Infinity Pool",
        "description": "Wake up to breathtaking ocean views in this luxurious beachfront villa. Featuring an infinity pool overlooking the Pacific, spacious living areas with floor-to-ceiling windows, a gourmet kitchen, and direct beach access. Perfect for families and groups looking for a premium coastal retreat.\n\nThe villa spans 3,200 sq ft with an open floor plan that seamlessly connects indoor and outdoor living. The master suite features a private balcony with panoramic ocean views. Each bedroom has en-suite bathrooms with rainfall showers.\n\nGuests enjoy complimentary beach chairs, surfboards, and snorkeling equipment. The outdoor area includes a BBQ station, fire pit, and a covered dining area for al fresco meals.",
        "property_type": "Villa",
        "category": "Beach",
        "price_per_night": 450,
        "cleaning_fee": 150,
        "service_fee": 85,
        "city": "Malibu",
        "state": "California",
        "country": "United States",
        "latitude": 34.0259,
        "longitude": -118.7798,
        "max_guests": 8,
        "bedrooms": 4,
        "beds": 5,
        "bathrooms": 3.5,
        "avg_rating": 4.95,
        "num_reviews": 128,
        "amenity_indices": [0, 1, 2, 3, 4, 5, 6, 8, 10, 13, 16, 19, 20, 21, 22, 24],
        "images": [
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 0,
        "title": "Luxury Beachhouse with Private Beach Access",
        "description": "Experience the ultimate beach getaway in this stunning beachhouse. Step right out onto pristine white sand from your private deck. Enjoy stunning sunsets from the wraparound porch while listening to waves crash against the shore.\n\nThis beautifully renovated beach house features an open-concept living area with vaulted ceilings, a fully equipped chef's kitchen, and large windows that flood every room with natural light.\n\nThe outdoor shower and beach rinse station make coming back from the beach a breeze. Kayaks and paddleboards are included for your use.",
        "property_type": "House",
        "category": "Beach",
        "price_per_night": 320,
        "cleaning_fee": 100,
        "service_fee": 60,
        "city": "Santa Cruz",
        "state": "California",
        "country": "United States",
        "latitude": 36.9741,
        "longitude": -122.0308,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 2,
        "avg_rating": 4.88,
        "num_reviews": 96,
        "amenity_indices": [0, 1, 2, 4, 5, 6, 10, 13, 16, 19, 20, 24],
        "images": [
            "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 1,
        "title": "Modern Downtown Loft with Skyline Views",
        "description": "Stay in the heart of the city in this stunning modern loft. Floor-to-ceiling windows offer breathtaking skyline views, while the industrial-chic design creates a sophisticated atmosphere perfect for business travelers or couples.\n\nThe open-plan living space features polished concrete floors, exposed brick walls, and contemporary furnishings. The fully equipped kitchen includes a premium coffee machine and wine fridge.\n\nLocated steps from the best restaurants, galleries, and nightlife. Building amenities include a rooftop terrace, gym, and 24-hour concierge.",
        "property_type": "Apartment",
        "category": "Trending",
        "price_per_night": 185,
        "cleaning_fee": 75,
        "service_fee": 35,
        "city": "New York",
        "state": "New York",
        "country": "United States",
        "latitude": 40.7128,
        "longitude": -74.0060,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "avg_rating": 4.92,
        "num_reviews": 215,
        "amenity_indices": [0, 1, 4, 5, 6, 7, 10, 12, 19, 20, 23, 24],
        "images": [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 2,
        "title": "Cozy Mountain Cabin with Hot Tub & Fireplace",
        "description": "Escape to this charming mountain cabin nestled among towering pines. Unwind in the private hot tub under the stars, warm up by the stone fireplace, and explore miles of hiking trails right from your doorstep.\n\nThe cabin features rustic wood interiors with modern amenities, a fully stocked kitchen for cozy meals, and a wraparound deck with mountain views. The loft bedroom has a king bed and skylight for stargazing.\n\nPerfect for romantic getaways or small family retreats. Ski resorts are just 15 minutes away in winter.",
        "property_type": "Cabin",
        "category": "Mountain",
        "price_per_night": 225,
        "cleaning_fee": 80,
        "service_fee": 42,
        "city": "Lake Tahoe",
        "state": "California",
        "country": "United States",
        "latitude": 39.0968,
        "longitude": -120.0324,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1.5,
        "avg_rating": 4.97,
        "num_reviews": 183,
        "amenity_indices": [0, 1, 4, 5, 6, 9, 10, 13, 15, 19, 20, 21, 22, 24],
        "images": [
            "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 1,
        "title": "Elegant Parisian Apartment near Eiffel Tower",
        "description": "Live the Parisian dream in this elegantly appointed apartment just steps from the Eiffel Tower. Classic Haussmann architecture meets modern luxury with herringbone parquet floors, ornate moldings, and contemporary furnishings.\n\nThe spacious living room opens to a private balcony with stunning views of the Iron Lady. The fully equipped kitchen is perfect for preparing French cuisine with fresh ingredients from the nearby market.\n\nExplore world-class museums, charming cafés, and iconic landmarks all within walking distance.",
        "property_type": "Apartment",
        "category": "Iconic cities",
        "price_per_night": 275,
        "cleaning_fee": 90,
        "service_fee": 52,
        "city": "Paris",
        "state": "Île-de-France",
        "country": "France",
        "latitude": 48.8566,
        "longitude": 2.3522,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1,
        "avg_rating": 4.91,
        "num_reviews": 342,
        "amenity_indices": [0, 1, 2, 4, 5, 6, 7, 19, 20, 23, 24, 25],
        "images": [
            "https://images.unsplash.com/photo-1550133730-695473e544be?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 2,
        "title": "Treehouse Retreat in the Redwoods",
        "description": "Experience something truly magical in this architectural treehouse suspended among ancient redwoods. Wake up at canopy level with birds singing and dappled sunlight filtering through the leaves.\n\nThe treehouse features a queen bed with premium linens, a compact kitchenette, and a bathroom with a composting toilet and outdoor shower. The wraparound deck offers 360-degree forest views.\n\nThis is a true digital detox experience — limited wifi is available at the main lodge, a 5-minute walk along a forest trail.",
        "property_type": "Treehouse",
        "category": "OMG!",
        "price_per_night": 195,
        "cleaning_fee": 65,
        "service_fee": 37,
        "city": "Guerneville",
        "state": "California",
        "country": "United States",
        "latitude": 38.5013,
        "longitude": -122.9960,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "avg_rating": 4.98,
        "num_reviews": 267,
        "amenity_indices": [1, 5, 10, 19, 20, 21, 24],
        "images": [
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1618767689160-da3fb810aad7?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 3,
        "title": "Santorini Cave House with Caldera Views",
        "description": "Stay in a traditional cave house carved into the volcanic cliffs of Santorini. This unique property offers unobstructed views of the famous caldera and the most spectacular sunsets in the world.\n\nThe whitewashed interior features curved cave ceilings, a plunge pool on the terrace, and contemporary Mediterranean decor. The kitchen is equipped with everything you need to prepare a Greek feast.\n\nLocated in the picturesque village of Oia, you'll be steps from galleries, restaurants, and the iconic blue-domed churches.",
        "property_type": "Cave",
        "category": "OMG!",
        "price_per_night": 380,
        "cleaning_fee": 120,
        "service_fee": 72,
        "city": "Santorini",
        "state": "South Aegean",
        "country": "Greece",
        "latitude": 36.3932,
        "longitude": 25.4615,
        "max_guests": 3,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "avg_rating": 4.96,
        "num_reviews": 189,
        "amenity_indices": [0, 1, 4, 6, 8, 17, 19, 20, 24],
        "images": [
            "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 0,
        "title": "Tropical Bali Villa with Rice Paddy Views",
        "description": "Immerse yourself in the tranquility of Bali in this stunning villa overlooking lush rice terraces. The open-air design connects you with nature while providing every modern comfort.\n\nFeatures include a private infinity pool, outdoor shower garden, fully equipped kitchen, and a yoga deck perfect for morning practice. Traditional Balinese architecture meets contemporary design.\n\nLocated in the artistic heart of Ubud, near temples, galleries, and the famous Monkey Forest. Daily breakfast with tropical fruits is included.",
        "property_type": "Villa",
        "category": "Tropical",
        "price_per_night": 155,
        "cleaning_fee": 45,
        "service_fee": 29,
        "city": "Ubud",
        "state": "Bali",
        "country": "Indonesia",
        "latitude": -8.5069,
        "longitude": 115.2625,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2,
        "avg_rating": 4.93,
        "num_reviews": 412,
        "amenity_indices": [0, 1, 4, 6, 8, 10, 13, 14, 19, 20, 24, 27],
        "images": [
            "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 3,
        "title": "Japanese Ryokan-Style Loft in Kyoto",
        "description": "Experience traditional Japanese hospitality in this beautifully restored machiya townhouse. Tatami mats, shoji screens, and a private zen garden create an authentic yet comfortable stay.\n\nThe property features a modern bathroom with a deep soaking tub (ofuro), a compact but well-equipped kitchen, and futon bedding on tatami floors. The private garden includes a tea ceremony area.\n\nLocated in the historic Gion district, surrounded by temples, tea houses, and geisha culture. Walking distance to the bamboo grove and Kinkaku-ji.",
        "property_type": "House",
        "category": "Historical homes",
        "price_per_night": 210,
        "cleaning_fee": 70,
        "service_fee": 40,
        "city": "Kyoto",
        "state": "Kyoto Prefecture",
        "country": "Japan",
        "latitude": 35.0116,
        "longitude": 135.7681,
        "max_guests": 3,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1,
        "avg_rating": 4.94,
        "num_reviews": 156,
        "amenity_indices": [0, 1, 4, 5, 6, 19, 20, 24, 25],
        "images": [
            "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 1,
        "title": "Penthouse Suite with Rooftop Terrace in Barcelona",
        "description": "Live the high life in this stunning penthouse in the Gothic Quarter. The expansive rooftop terrace offers 360-degree views of Barcelona's skyline, including glimpses of the Sagrada Familia and the Mediterranean Sea.\n\nThe interior features contemporary Spanish design with Gaudi-inspired touches, high ceilings, and abundant natural light. The modern kitchen opens to an entertainment area perfect for hosting.\n\nSteps from Las Ramblas, the Gothic Cathedral, and world-class dining. The Barceloneta beach is a short walk away.",
        "property_type": "Apartment",
        "category": "Iconic cities",
        "price_per_night": 295,
        "cleaning_fee": 95,
        "service_fee": 56,
        "city": "Barcelona",
        "state": "Catalonia",
        "country": "Spain",
        "latitude": 41.3851,
        "longitude": 2.1734,
        "max_guests": 5,
        "bedrooms": 2,
        "beds": 3,
        "bathrooms": 2,
        "avg_rating": 4.89,
        "num_reviews": 278,
        "amenity_indices": [0, 1, 2, 3, 4, 5, 6, 7, 10, 19, 20, 23, 24],
        "images": [
            "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 2,
        "title": "A-Frame Cabin in the Pacific Northwest",
        "description": "Escape to this charming A-frame cabin surrounded by old-growth forest in the Pacific Northwest. The dramatic floor-to-ceiling windows frame towering Douglas firs and let in golden forest light.\n\nThe cozy interior features a wood-burning stove, a loft bedroom accessed by a custom ladder, and a well-equipped kitchen. Outside, a fire pit and Adirondack chairs invite evenings under the stars.\n\nMinutes from hiking trails, waterfalls, and a pristine lake. A true nature lover's paradise with modern comforts.",
        "property_type": "Cabin",
        "category": "Cabins",
        "price_per_night": 175,
        "cleaning_fee": 60,
        "service_fee": 33,
        "city": "Hood River",
        "state": "Oregon",
        "country": "United States",
        "latitude": 45.7054,
        "longitude": -121.5215,
        "max_guests": 4,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1,
        "avg_rating": 4.96,
        "num_reviews": 204,
        "amenity_indices": [0, 1, 5, 6, 10, 13, 15, 19, 20, 21, 22, 24, 27],
        "images": [
            "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 3,
        "title": "Desert Adobe Retreat in Joshua Tree",
        "description": "Find serenity in this authentic adobe home in the Joshua Tree desert. Minimalist design meets desert luxury with natural materials, earth tones, and expansive desert views from every window.\n\nThe property features a private outdoor soaking tub, a stargazing deck, and a fire pit perfect for desert evenings. Inside, the open floor plan flows naturally between living, dining, and sleeping areas.\n\nExplore Joshua Tree National Park, just 10 minutes away. The area's famous dark skies offer incredible stargazing opportunities.",
        "property_type": "House",
        "category": "Desert",
        "price_per_night": 245,
        "cleaning_fee": 85,
        "service_fee": 46,
        "city": "Joshua Tree",
        "state": "California",
        "country": "United States",
        "latitude": 34.1347,
        "longitude": -116.3131,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1,
        "avg_rating": 4.90,
        "num_reviews": 167,
        "amenity_indices": [0, 1, 4, 5, 6, 9, 10, 13, 19, 20, 24],
        "images": [
            "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 0,
        "title": "Lakefront Cottage with Dock & Canoe",
        "description": "Enjoy waterfront living at this cozy cottage on a crystal-clear lake. The private dock includes a canoe and kayaks, perfect for exploring the scenic shoreline. Watch loons fish at sunset from the screened porch.\n\nThe cottage features knotty pine interiors, a stone fireplace, and a fully equipped kitchen. The large deck overlooks the lake with a BBQ grill and outdoor dining area.\n\nSwim, fish, or simply relax by the water. In autumn, the surrounding forest blazes with spectacular fall colors.",
        "property_type": "Cottage",
        "category": "Lakefront",
        "price_per_night": 189,
        "cleaning_fee": 65,
        "service_fee": 36,
        "city": "Lake Placid",
        "state": "New York",
        "country": "United States",
        "latitude": 44.2795,
        "longitude": -73.9799,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 2,
        "avg_rating": 4.87,
        "num_reviews": 142,
        "amenity_indices": [0, 1, 5, 6, 10, 13, 15, 17, 19, 20, 21, 24, 27],
        "images": [
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 1,
        "title": "Ski Chalet with Mountain Panorama",
        "description": "Hit the slopes from this luxury ski chalet with ski-in/ski-out access. After a day of skiing, warm up in the private hot tub or by the grand stone fireplace with a glass of wine.\n\nThe chalet features four bedrooms, each with stunning mountain views, a gourmet kitchen, and a spacious living area with vaulted timber ceilings. The boot room and ski storage make gear management effortless.\n\nSummer brings world-class mountain biking, hiking, and wildflower meadows. Year-round adventure awaits.",
        "property_type": "Chalet",
        "category": "Skiing",
        "price_per_night": 420,
        "cleaning_fee": 140,
        "service_fee": 79,
        "city": "Whistler",
        "state": "British Columbia",
        "country": "Canada",
        "latitude": 50.1163,
        "longitude": -122.9574,
        "max_guests": 8,
        "bedrooms": 4,
        "beds": 5,
        "bathrooms": 3,
        "avg_rating": 4.94,
        "num_reviews": 198,
        "amenity_indices": [0, 1, 2, 3, 4, 5, 6, 9, 10, 12, 15, 18, 19, 20, 21, 22, 24],
        "images": [
            "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 2,
        "title": "Converted Barn Farmstay in Tuscany",
        "description": "Live the Italian countryside dream in this beautifully converted stone barn on a working olive farm in the rolling hills of Tuscany. Original stone walls and timber beams meet modern Italian design.\n\nThe property includes access to the farm's olive oil and wine. The large garden features a pool with vineyard views, an outdoor kitchen, and endless photo opportunities among the cypress-lined roads.\n\nCooking classes and wine tastings can be arranged. Florence and Siena are both within an hour's drive.",
        "property_type": "Farm stay",
        "category": "Countryside",
        "price_per_night": 198,
        "cleaning_fee": 70,
        "service_fee": 37,
        "city": "Florence",
        "state": "Tuscany",
        "country": "Italy",
        "latitude": 43.7696,
        "longitude": 11.2558,
        "max_guests": 6,
        "bedrooms": 3,
        "beds": 4,
        "bathrooms": 2,
        "avg_rating": 4.91,
        "num_reviews": 223,
        "amenity_indices": [0, 1, 2, 4, 5, 6, 8, 10, 13, 14, 19, 20, 24, 26, 27],
        "images": [
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 3,
        "title": "Tiny House with Big Views in New Zealand",
        "description": "Less is more in this architecturally stunning tiny house perched on a hilltop overlooking the Remarkables mountain range. Large windows blur the boundary between indoors and the spectacular landscape.\n\nThe compact but cleverly designed space includes a queen loft bed, compact kitchen, full bathroom, and a deck that feels like it extends into the mountains. Solar-powered and eco-friendly.\n\nPerfect for couples seeking a unique escape. Queenstown is just 20 minutes away with adventure activities galore.",
        "property_type": "Tiny home",
        "category": "OMG!",
        "price_per_night": 165,
        "cleaning_fee": 50,
        "service_fee": 31,
        "city": "Queenstown",
        "state": "Otago",
        "country": "New Zealand",
        "latitude": -45.0312,
        "longitude": 168.6626,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "avg_rating": 4.99,
        "num_reviews": 89,
        "amenity_indices": [0, 1, 5, 6, 10, 19, 20, 24],
        "images": [
            "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 0,
        "title": "Houseboat on the Amsterdam Canals",
        "description": "Stay on the water in this charming houseboat on one of Amsterdam's most beautiful canals. Watch boats glide by from your private deck while enjoying the quintessential Amsterdam experience.\n\nThe houseboat is surprisingly spacious with a cozy living room, equipped kitchen, and a bedroom with water views. The gentle rocking of the boat adds to the unique atmosphere.\n\nBikes are provided for exploring the city like a local. Museums, markets, and cafes are all within easy cycling distance.",
        "property_type": "Houseboat",
        "category": "OMG!",
        "price_per_night": 199,
        "cleaning_fee": 75,
        "service_fee": 38,
        "city": "Amsterdam",
        "state": "North Holland",
        "country": "Netherlands",
        "latitude": 52.3676,
        "longitude": 4.9041,
        "max_guests": 2,
        "bedrooms": 1,
        "beds": 1,
        "bathrooms": 1,
        "avg_rating": 4.88,
        "num_reviews": 175,
        "amenity_indices": [0, 1, 4, 5, 6, 17, 19, 20, 24],
        "images": [
            "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 1,
        "title": "Luxury Safari Lodge in South Africa",
        "description": "Experience the African bush in ultimate luxury at this private safari lodge in the Greater Kruger area. Fall asleep to the sounds of the wild and wake up to giraffes grazing outside your window.\n\nThe lodge features floor-to-ceiling glass walls, a private plunge pool overlooking the bush, an outdoor shower, and elegant African-inspired decor. Daily game drives are included.\n\nMeals are prepared by a private chef using locally sourced ingredients. Sundowner cocktails on the viewing deck are unforgettable.",
        "property_type": "Villa",
        "category": "Trending",
        "price_per_night": 550,
        "cleaning_fee": 0,
        "service_fee": 104,
        "city": "Kruger Park",
        "state": "Limpopo",
        "country": "South Africa",
        "latitude": -24.0176,
        "longitude": 31.4855,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 2,
        "avg_rating": 4.97,
        "num_reviews": 87,
        "amenity_indices": [0, 1, 4, 6, 8, 14, 19, 20, 24],
        "images": [
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 2,
        "title": "Cliff-Edge Glass House in Norway",
        "description": "Perched on the edge of a dramatic fjord cliff, this architectural glass house offers views that will take your breath away. The minimalist Scandinavian design lets nature take center stage.\n\nFloor-to-ceiling triple-glazed windows frame the fjord below and the mountains beyond. The house features underfloor heating, a sauna, and a hot tub on the deck. Northern Lights are visible in winter.\n\nHike to hidden waterfalls, kayak the fjord, or simply contemplate the view with a cup of Norwegian coffee.",
        "property_type": "House",
        "category": "Amazing views",
        "price_per_night": 340,
        "cleaning_fee": 110,
        "service_fee": 64,
        "city": "Bergen",
        "state": "Vestland",
        "country": "Norway",
        "latitude": 60.3913,
        "longitude": 5.3221,
        "max_guests": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": 1.5,
        "avg_rating": 4.95,
        "num_reviews": 112,
        "amenity_indices": [0, 1, 4, 5, 6, 9, 10, 19, 20, 23, 24],
        "images": [
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=600&fit=crop",
        ],
    },
    {
        "host_idx": 3,
        "title": "Art Deco Apartment in Miami Beach",
        "description": "Step back into the glamour of old Miami in this beautifully restored Art Deco apartment in South Beach. Vintage tile floors, curved archways, and pastel colors create an Instagram-worthy space.\n\nThe apartment is steps from the beach and Ocean Drive. The rooftop pool offers stunning ocean views and the perfect spot for watching Miami's legendary sunsets.\n\nExplore the vibrant nightlife, world-class dining, and the Wynwood art district. This is Miami living at its finest.",
        "property_type": "Apartment",
        "category": "Beach",
        "price_per_night": 220,
        "cleaning_fee": 80,
        "service_fee": 42,
        "city": "Miami Beach",
        "state": "Florida",
        "country": "United States",
        "latitude": 25.7907,
        "longitude": -80.1300,
        "max_guests": 4,
        "bedrooms": 1,
        "beds": 2,
        "bathrooms": 1,
        "avg_rating": 4.85,
        "num_reviews": 312,
        "amenity_indices": [0, 1, 2, 4, 6, 8, 10, 12, 16, 19, 20, 23, 24],
        "images": [
            "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop",
        ],
    },
]

REVIEWS_DATA = [
    {"text": "Absolutely stunning property! The views were even better than the photos. Host was incredibly responsive and helpful. Would definitely stay again!", "rating": 5.0},
    {"text": "Perfect getaway. The place was immaculate and had everything we needed. The location was ideal for exploring the area.", "rating": 4.9},
    {"text": "Great location, beautiful space. The kitchen was well-equipped and we loved cooking meals together. Minor issue with hot water but host fixed it quickly.", "rating": 4.7},
    {"text": "We had the most amazing time! The property exceeded our expectations. Such attention to detail in every corner.", "rating": 5.0},
    {"text": "Lovely stay, very comfortable and clean. The neighborhood was quiet and peaceful. Would recommend to friends.", "rating": 4.8},
    {"text": "One of the best Airbnb experiences we've had. The host thought of everything. The welcome basket was a wonderful touch!", "rating": 5.0},
    {"text": "Incredible property in an amazing location. We didn't want to leave! The sunset views from the terrace were unforgettable.", "rating": 4.9},
    {"text": "Very well-maintained and beautifully decorated. Close to everything but felt like a private retreat. Highly recommend!", "rating": 4.8},
]


def seed_database(db: Session):
    """Seed the database with sample data."""
    # Check if already seeded
    if db.query(User).count() > 0:
        return

    print("[SEED] Seeding database...")

    # Create amenities
    amenities = []
    for data in AMENITIES_DATA:
        amenity = Amenity(**data)
        db.add(amenity)
        amenities.append(amenity)
    db.flush()

    # Create users
    users = []
    for data in USERS_DATA:
        user = User(
            email=data["email"],
            hashed_password=get_password_hash(data["password"]),
            first_name=data["first_name"],
            last_name=data["last_name"],
            avatar_url=data["avatar_url"],
            bio=data["bio"],
            is_host=data["is_host"],
            is_superhost=data["is_superhost"],
        )
        db.add(user)
        users.append(user)
    db.flush()

    # Create listings
    listings = []
    for data in LISTINGS_DATA:
        host = users[data["host_idx"]]
        listing = Listing(
            host_id=host.id,
            title=data["title"],
            description=data["description"],
            property_type=data["property_type"],
            category=data["category"],
            price_per_night=data["price_per_night"],
            cleaning_fee=data["cleaning_fee"],
            service_fee=data["service_fee"],
            city=data["city"],
            state=data["state"],
            country=data["country"],
            latitude=data["latitude"],
            longitude=data["longitude"],
            max_guests=data["max_guests"],
            bedrooms=data["bedrooms"],
            beds=data["beds"],
            bathrooms=data["bathrooms"],
            avg_rating=data["avg_rating"],
            num_reviews=data["num_reviews"],
        )
        db.add(listing)
        db.flush()

        # Add images
        for i, url in enumerate(data["images"]):
            img = ListingImage(listing_id=listing.id, url=url, position=i)
            db.add(img)

        # Add amenities
        for idx in data["amenity_indices"]:
            if idx < len(amenities):
                listing.amenities.append(amenities[idx])

        listings.append(listing)

    db.flush()

    # Create some bookings (guest = user[4])
    guest = users[4]
    today = datetime.date.today()

    bookings_data = [
        {"listing_idx": 0, "offset_start": 10, "offset_end": 15, "guests": 4},
        {"listing_idx": 2, "offset_start": -5, "offset_end": -2, "guests": 2},
        {"listing_idx": 4, "offset_start": 20, "offset_end": 27, "guests": 3},
        {"listing_idx": 7, "offset_start": 30, "offset_end": 35, "guests": 2},
    ]

    bookings = []
    for bdata in bookings_data:
        listing = listings[bdata["listing_idx"]]
        check_in = today + datetime.timedelta(days=bdata["offset_start"])
        check_out = today + datetime.timedelta(days=bdata["offset_end"])
        nights = (check_out - check_in).days
        total = listing.price_per_night * nights + listing.cleaning_fee + listing.service_fee

        status = "completed" if bdata["offset_start"] < 0 else "confirmed"

        booking = Booking(
            listing_id=listing.id,
            guest_id=guest.id,
            check_in=check_in,
            check_out=check_out,
            num_guests=bdata["guests"],
            total_price=round(total, 2),
            status=status,
        )
        db.add(booking)
        bookings.append(booking)

    db.flush()

    # Create reviews for listings
    import random
    review_authors = [users[4]]  # Guest user writes reviews

    for listing in listings:
        # Add 2-3 reviews per listing
        num_reviews = random.randint(2, 3)
        for i in range(num_reviews):
            review_data = REVIEWS_DATA[i % len(REVIEWS_DATA)]
            review = Review(
                listing_id=listing.id,
                author_id=users[4].id,
                rating=review_data["rating"],
                cleanliness=round(random.uniform(4.5, 5.0), 1),
                accuracy=round(random.uniform(4.5, 5.0), 1),
                communication=round(random.uniform(4.5, 5.0), 1),
                location_rating=round(random.uniform(4.5, 5.0), 1),
                check_in_rating=round(random.uniform(4.5, 5.0), 1),
                value=round(random.uniform(4.3, 5.0), 1),
                comment=review_data["text"],
                created_at=datetime.datetime.utcnow() - datetime.timedelta(days=random.randint(1, 180)),
            )
            db.add(review)

    # Create a wishlist for the guest
    wishlist = Wishlist(user_id=guest.id, name="Dream Destinations")
    db.add(wishlist)
    db.flush()
    wishlist.listings.extend([listings[0], listings[3], listings[6], listings[7]])

    db.commit()
    print("[SEED] Database seeded successfully!")
